trigger: none

pool: Azure Pipelines

steps:
- task: TerraformInstaller@1
  displayName: 'Terraform Installer'
  inputs:
    terraformVersion: 'latest'
- script: |
    terraform --version
  displayName: 'Check Terraform Version'
- script: |
    which terraform
    ls -l /opt/hostedtoolcache/terraform/1.13.1/x64/
  displayName: 'Debug Terraform Path'
- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(workDir)'
    backendServiceArm: 'redo_ADO'
    backendAzureRmResourceGroupName: 'RG_SP'
    backendAzureRmStorageAccountName: 'stgsp'
    backendAzureRmContainerName: 'contsp'
    backendAzureRmKey: 'devsp.tfstate'
- task: TerraformTask@5
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_dev'
- task: TerraformTask@5
  displayName: 'Terraform Fmt'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_dev'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'redo_ADO'
- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_dev'
    environmentServiceNameAzureRM: 'redo_ADO'