# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: Azure Pipelines

steps:

- task: TerraformInstaller@1
  displayName: 'Terraform Install'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName : 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_dev'
    backendServiceArm: 'workload_identity_federation_connection'
    backendAzureRmResourceGroupName: 'rg-pipeline'
    backendAzureRmStorageAccountName: 'stgpipeline'
    backendAzureRmContainerName: 'contpipeline'
    backendAzureRmKey: 'pipeline.tfstate'

- task: TerraformTask@5
  displayName : 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_dev'


- task: TerraformTask@5
  displayName: 'Terraform fmt'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_dev'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'workload_identity_federation_connection'


- task: TerraformTask@5
  displayName: 'Terraform plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_dev'
    environmentServiceNameAzureRM: 'workload_identity_federation_connection'

    






